# Generated by Django 4.1 on 2022-09-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_board", models.TextField(max_length=500, verbose_name="首頁公布欄")),
                (
                    "checkout_board",
                    models.TextField(max_length=500, verbose_name="結帳公布欄"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="收件人")),
                ("phone", models.CharField(max_length=12, verbose_name="手機號碼")),
                (
                    "mail",
                    models.EmailField(max_length=254, null=True, verbose_name="電子信箱"),
                ),
                ("zipcode", models.CharField(max_length=6, verbose_name="郵遞區號")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                ("complete", models.BooleanField(default=False)),
                (
                    "message",
                    models.CharField(max_length=200, null=True, verbose_name="備註欄"),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="產品名")),
                ("price", models.IntegerField(verbose_name="原價")),
                ("promotion", models.IntegerField(verbose_name="特價")),
                ("detail", models.TextField(max_length=500, verbose_name="商品說明")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images", verbose_name="圖片"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images")),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
