# Generated by Django 4.1.2 on 2023-02-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.CharField(
                choices=[("是", "是"), ("否", "否")],
                default="否",
                max_length=20,
                verbose_name="已寄出訂單",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transfer",
            field=models.CharField(
                choices=[("是", "是"), ("否", "否")],
                default="否",
                max_length=20,
                verbose_name="收到款項",
            ),
        ),
    ]
