# Generated by Django 4.0.1 on 2022-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='主標')),
                ('description', models.TextField(max_length=200, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel', verbose_name='圖片')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='備註欄'),
        ),
    ]
