# Generated by Django 4.0.1 on 2022-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_carousel_alter_order_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='優惠券名稱')),
                ('code', models.CharField(max_length=10, verbose_name='優惠碼')),
                ('price', models.IntegerField(max_length=5, verbose_name='折扣費用')),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='主標'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=700, verbose_name='商品說明'),
        ),
    ]
