# Generated by Django 4.0.1 on 2022-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_spcode_alter_carousel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='優惠券名稱')),
                ('code', models.CharField(max_length=10, verbose_name='優惠碼')),
                ('discount', models.IntegerField(max_length=5, verbose_name='折扣費用')),
                ('valid_from', models.DateTimeField(verbose_name='開始日期')),
                ('valid_to', models.DateTimeField(verbose_name='結束日期')),
                ('active', models.BooleanField(verbose_name='啟用')),
            ],
        ),
        migrations.DeleteModel(
            name='SPcode',
        ),
    ]
