# Generated by Django 4.0.1 on 2022-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coupon_delete_spcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='運送方式')),
                ('fee', models.IntegerField(verbose_name='運費')),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(verbose_name='折扣費用'),
        ),
    ]
