# Generated by Django 4.0.1 on 2022-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delivery_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ManyToManyField(blank=True, to='shop.Delivery'),
        ),
    ]
