# Generated by Django 4.0.1 on 2022-10-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10, verbose_name='運送方式')),
                ('fee', models.IntegerField(verbose_name='運費')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.EmailField(help_text='請輸入有效的電子信箱', max_length=254, null=True, verbose_name='電子信箱'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery',
            field=models.ManyToManyField(to='shop.DeliverCompany', verbose_name='送貨方式'),
        ),
    ]
