# Generated by Django 4.0.1 on 2022-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delivercompany_remove_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_store',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='店到店門市'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery',
            field=models.ManyToManyField(to='shop.DeliverCompany', verbose_name='選擇送貨方式'),
        ),
    ]
