# Generated by Django 4.0.1 on 2022-10-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_delivery_store_alter_delivery_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='郵遞區號'),
        ),
    ]
