# Generated by Django 4.0.1 on 2022-10-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_address_alter_order_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='運送超市'),
        ),
    ]
