# Generated by Django 4.0.1 on 2022-10-20 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_delivery_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='優惠卷折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='運費'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='結帳金額'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='收到款項'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='已寄出訂單'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
