# Generated by Django 4.1.2 on 2022-10-23 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_order_coupon_price_order_delivery_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfername", models.CharField(max_length=10, verbose_name="匯款人姓名")),
                ("transferNums", models.IntegerField(verbose_name="帳號後五碼")),
                ("transferPrice", models.IntegerField(verbose_name="匯款金額")),
                ("transferdate", models.DateTimeField(verbose_name="匯款日期")),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="訂單編號",
            ),
        ),
    ]
