# Generated by Django 4.1.2 on 2022-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_paymentreport_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreport",
            name="transferdate",
            field=models.CharField(max_length=15, verbose_name="匯款日期"),
        ),
    ]
