# Generated by Django 4.1.2 on 2022-10-23 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_paymentreport_transferdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreport",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentreport",
            name="transferNums",
            field=models.CharField(max_length=15, verbose_name="帳號後五碼"),
        ),
        migrations.AlterField(
            model_name="paymentreport",
            name="transferPrice",
            field=models.CharField(max_length=15, verbose_name="匯款金額"),
        ),
    ]
