# Generated by Django 4.1.2 on 2022-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_order_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(
                choices=[(False, "No"), (True, "Yes")],
                default=False,
                verbose_name="已寄出訂單",
            ),
        ),
    ]
