# Generated by Django 4.1.2 on 2022-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_order_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.CharField(
                choices=[("否", "否"), ("是", "是")],
                default="否",
                max_length=20,
                verbose_name="已寄出訂單",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transfer",
            field=models.CharField(
                choices=[("否", "否"), ("是", "是")],
                default="否",
                max_length=20,
                verbose_name="收到款項",
            ),
        ),
    ]
